services:
  - type: web
    name: messaging-socket-server
    env: node
    buildCommand: npm install
    startCommand: node socket-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 5000
